# This Dockerfile is a used by CI to publish openshift/origin-v4.0:installer

FROM openshift/origin-release:golang-1.10
WORKDIR /go/src/github.com/openshift/installer
COPY . .
RUN hack/build.sh && hack/get-terraform.sh

RUN mkdir /home/user && cp bin/* /usr/bin
ENV HOME /home/user
WORKDIR /home/user
